/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d4dcd7",
        "surface-container-high": "#e2eae5",
        "on-primary-fixed-variant": "#454749",
        "error": "#ba1a1a",
        "surface-bright": "#f3fbf6",
        "background": "#f3fbf6",
        "on-tertiary-container": "#1f7a6c",
        "outline": "#737875",
        "on-secondary-container": "#5f665d",
        "tertiary": "#006b5e",
        "on-primary-container": "#6b6d6f",
        "inverse-primary": "#c6c6c9",
        "on-surface-variant": "#434845",
        "surface-container-low": "#edf5f0",
        "secondary-fixed-dim": "#c1c9bd",
        "inverse-surface": "#2a322f",
        "outline-variant": "#c3c7c4",
        "on-surface": "#161d1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "surface-variant": "#dce4df",
        "surface-container-highest": "#dce4df",
        "on-primary-fixed": "#1a1c1e",
        "on-background": "#161d1a",
        "secondary-fixed": "#dee5d8",
        "surface-tint": "#5d5e61",
        "tertiary-container": "#b1ffef",
        "on-tertiary-fixed-variant": "#005046",
        "on-tertiary-fixed": "#00201b",
        "tertiary-fixed": "#9ff2e1",
        "surface": "#f3fbf6",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#424940",
        "secondary-container": "#dee5d8",
        "on-secondary-fixed": "#171d16",
        "primary-container": "#f0f0f2",
        "surface-container": "#e8f0eb",
        "primary": "#5d5e61",
        "primary-fixed-dim": "#c6c6c9",
        "inverse-on-surface": "#ebf3ee",
        "tertiary-fixed-dim": "#83d5c5",
        "secondary": "#596057",
        "primary-fixed": "#e2e2e5",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
}
